### ISSUE TITLE
Move action into it's own repository

### ISSUE THREAD

**Issue by vsoch** [rseng/awesome-rseng#12]

**Comment by vsoch** [comment]
We should move the action into it's own repository (and it will be run here). The reason is simple - modularity and naming. Right now we have:

```
    - name: Generate First Issues
      uses: rseng/awesome-rseng@b8c2ad60fa9d33331617b98dc7351695e7da253f
      with:
        repos-file: '.github/repos.txt'
        token: ${{ secrets.GITHUB_TOKEN }}
```

And it would really read more nicely as:

```
    - name: Generate First Issues
      uses: rseng/good-first-issues@b8c2ad60fa9d33331617b98dc7351695e7da253f
      with:
        repos-file: '.github/repos.txt'
        token: ${{ secrets.GITHUB_TOKEN }}
```

And then it will be easier to expose the documentation for it (which is currently at the bottom of the README here). The .github/repos.txt will remain here, of course.
